/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ionossdk
// KubernetesNodePoolPropertiesForPut struct for KubernetesNodePoolPropertiesForPut
type KubernetesNodePoolPropertiesForPut struct {
	// A Kubernetes Node Pool Name. Valid Kubernetes Node Pool name must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.
	Name *string `json:"name,omitempty"` /* nullable: false */
	// A valid uuid of the datacenter on which user has access
	DatacenterId *string `json:"datacenterId,omitempty"` /* nullable: false */
	// Number of nodes part of the Node Pool
	NodeCount *int32 `json:"nodeCount,omitempty"` /* nullable: false */
	// A valid cpu family name
	CpuFamily *string `json:"cpuFamily,omitempty"` /* nullable: false */
	// Number of cores for node
	CoresCount *int32 `json:"coresCount,omitempty"` /* nullable: false */
	// RAM size for node, minimum size 2048MB is recommended. Ram size must be set to multiple of 1024MB.
	RamSize *int32 `json:"ramSize,omitempty"` /* nullable: false */
	// The availability zone in which the server should exist
	AvailabilityZone *string `json:"availabilityZone,omitempty"` /* nullable: false */
	// Hardware type of the volume
	StorageType *string `json:"storageType,omitempty"` /* nullable: false */
	// The size of the volume in GB. The size should be greater than 10GB.
	StorageSize *int32 `json:"storageSize,omitempty"` /* nullable: false */
	// The kubernetes version in which a nodepool is running. This imposes restrictions on what kubernetes versions can be run in a cluster's nodepools. Additionally, not all kubernetes versions are viable upgrade targets for all prior versions.
	K8sVersion *string `json:"k8sVersion,omitempty"` /* nullable: false */
	MaintenanceWindow *KubernetesMaintenanceWindow `json:"maintenanceWindow,omitempty"` /* nullable: false */
	AutoScaling *KubernetesAutoScaling `json:"autoScaling,omitempty"` /* nullable: false */
	// array of additional LANs attached to worker nodes
	Lans *[]KubernetesNodePoolLan `json:"lans,omitempty"` /* nullable: false */
}
