/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ionossdk
// NicProperties struct for NicProperties
type NicProperties struct {
	// A name of that resource
	Name *string `json:"name,omitempty"` /* nullable: false */
	// The MAC address of the NIC
	Mac *string `json:"mac,omitempty"` /* nullable: false */
	// Collection of IP addresses assigned to a nic. Explicitly assigned public IPs need to come from reserved IP blocks, Passing value null or empty array will assign an IP address automatically.
	Ips *[]string `json:"ips,omitempty"` /* nullable: false */
	// Indicates if the nic will reserve an IP using DHCP
	Dhcp *bool `json:"dhcp,omitempty"` /* nullable: false */
	// The LAN ID the NIC will sit on. If the LAN ID does not exist it will be implicitly created
	Lan *int32 `json:"lan,omitempty"` /* nullable: false */
	// Activate or deactivate the firewall. By default an active firewall without any defined rules will block all incoming network traffic except for the firewall rules that explicitly allows certain protocols, ip addresses and ports.
	FirewallActive *bool `json:"firewallActive,omitempty"` /* nullable: false */
	// Indicates if NAT is enabled on this NIC
	Nat *bool `json:"nat,omitempty"` /* nullable: false */
}
