/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ionossdk
// UserProperties struct for UserProperties
type UserProperties struct {
	// first name of the user
	Firstname *string `json:"firstname,omitempty"` /* nullable: false */
	// last name of the user
	Lastname *string `json:"lastname,omitempty"` /* nullable: false */
	// email address of the user
	Email *string `json:"email,omitempty"` /* nullable: false */
	// indicates if the user has admin rights or not
	Administrator *bool `json:"administrator,omitempty"` /* nullable: false */
	// indicates if secure authentication should be forced on the user or not
	ForceSecAuth *bool `json:"forceSecAuth,omitempty"` /* nullable: false */
	// indicates if secure authentication is active for the user or not
	SecAuthActive *bool `json:"secAuthActive,omitempty"` /* nullable: false */
	// Canonical (S3) id of the user for a given identity
	S3CanonicalUserId *string `json:"s3CanonicalUserId,omitempty"` /* nullable: false */
	// User password
	Password *string `json:"password,omitempty"` /* nullable: false */
}
