/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ionossdk
import (
	"time"
)
// DatacenterElementMetadata struct for DatacenterElementMetadata
type DatacenterElementMetadata struct {
	// Resource's Entity Tag as defined in http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.11 . Entity Tag is also added as an 'ETag response header to requests which don't use 'depth' parameter. 
	Etag *string `json:"etag,omitempty"` /* nullable: false */
	// The last time the resource was created
	CreatedDate *time.Time `json:"createdDate,omitempty"` /* nullable: false */
	// The user who created the resource.
	CreatedBy *string `json:"createdBy,omitempty"` /* nullable: false */
	// The user id of the user who has created the resource.
	CreatedByUserId *string `json:"createdByUserId,omitempty"` /* nullable: false */
	// The last time the resource has been modified
	LastModifiedDate *time.Time `json:"lastModifiedDate,omitempty"` /* nullable: false */
	// The user who last modified the resource.
	LastModifiedBy *string `json:"lastModifiedBy,omitempty"` /* nullable: false */
	// The user id of the user who has last modified the resource.
	LastModifiedByUserId *string `json:"lastModifiedByUserId,omitempty"` /* nullable: false */
	// State of the resource. *AVAILABLE* There are no pending modification requests for this item; *BUSY* There is at least one modification request pending and all following requests will be queued; *INACTIVE* Resource has been de-provisioned; *DEPLOYING* Resource state DEPLOYING - relevant for Kubernetes cluster/nodepool; *ACTIVE* Resource state ACTIVE - relevant for Kubernetes cluster/nodepool; *FAILED* Resource state FAILED - relevant for Kubernetes cluster/nodepool; *SUSPENDED* Resource state SUSPENDED - relevant for Kubernetes cluster/nodepool; *FAILED_SUSPENDED* Resource state FAILED_SUSPENDED - relevant for Kubernetes cluster; *UPDATING* Resource state UPDATING - relevant for Kubernetes cluster/nodepool; *FAILED_UPDATING* Resource state FAILED_UPDATING - relevant for Kubernetes cluster/nodepool; *DESTROYING* Resource state DESTROYING - relevant for Kubernetes cluster; *FAILED_DESTROYING* Resource state FAILED_DESTROYING - relevant for Kubernetes cluster/nodepool; *TERMINATED* Resource state TERMINATED - relevant for Kubernetes cluster/nodepool
	State *string `json:"state,omitempty"` /* nullable: false */
}
