/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ionossdk
// Type the model 'Type'
type Type string

// List of Type
const (
	DATACENTER Type = "datacenter"
	SERVER Type = "server"
	VOLUME Type = "volume"
	NIC Type = "nic"
	LOADBALANCER Type = "loadbalancer"
	LOCATION Type = "location"
	FIREWALL_RULE Type = "firewall-rule"
	IMAGE Type = "image"
	SNAPSHOT Type = "snapshot"
	LAN Type = "lan"
	IPBLOCK Type = "ipblock"
	PCC Type = "pcc"
	CONTRACT Type = "contract"
	USER Type = "user"
	GROUP Type = "group"
	COLLECTION Type = "collection"
	RESOURCE Type = "resource"
	REQUEST Type = "request"
	REQUEST_STATUS Type = "request-status"
	S3KEY Type = "s3key"
	BACKUPUNIT Type = "backupunit"
	LABEL Type = "label"
	K8S Type = "k8s"
	NODEPOOL Type = "nodepool"
)
