/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ionossdk
// DatacenterProperties struct for DatacenterProperties
type DatacenterProperties struct {
	// A name of that resource
	Name *string `json:"name,omitempty"` /* nullable: false */
	// A description for the datacenter, e.g. staging, production
	Description *string `json:"description,omitempty"` /* nullable: false */
	// The physical location where the datacenter will be created. This will be where all of your servers live. Property cannot be modified after datacenter creation (disallowed in update requests)
	Location *string `json:"location,omitempty"` /* nullable: false */
	// The version of that Data Center. Gets incremented with every change
	Version *int32 `json:"version,omitempty"` /* nullable: false */
	// List of features supported by the location this data center is part of
	Features *[]string `json:"features,omitempty"` /* nullable: false */
	// Boolean value representing if the data center requires extra protection e.g. two factor protection
	SecAuthProtection *bool `json:"secAuthProtection,omitempty"` /* nullable: false */
}
